spring:
  application:
    name: saep

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saep
    username: root
    password: root

server:
  port: 9000
  error:
    include-stacktrace: never



